[env:ESP32-S3-DevKitC-1-N16R8]
platform = https://github.com/pioarduino/platform-espressif32.git


board_build.partitions = boards/partitions.csv   ; 16MB Flash
board = ESP32-S3-DevKitC-1-N16R8 ; 16 MB Flash, 8MB octo PSRAM





framework = arduino
monitor_speed = 115200
monitor_rts     = 0
monitor_dtr     = 0
upload_speed    = 921600


build_flags =
        -D CORE_DEBUG_LEVEL=1                    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
        -D CONFIG_ARDUHAL_LOG_COLORS=1
        -D ARDUINO_RUNNING_CORE=0                ; Arduino Runs On Core (setup, loop)
        -D ARDUINO_EVENT_RUNNING_CORE=0          ; Events Run On Core
        -D BOARD_HAS_PSRAM=1


lib_deps =
    https://github.com/lovyan03/LovyanGFX
    https://github.com/tzapu/WiFiManager
    https://github.com/ESP32Async/ESPAsyncWebServer
    https://github.com/bblanchon/ArduinoJson